name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o zsafe

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o zsafe.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            zsafe
            zsafe.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
